name: Build and Zip WPF App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild GameTheoryUtility/GameTheoryUtility.csproj /t:Restore

      - name: Build with MSBuild to Custom Output
        run: msbuild GameTheoryUtility/GameTheoryUtility.csproj /t:Build /p:Configuration=Release /p:OutputPath=out

      - name: Zip Output
        run: Compress-Archive -Path out\* -DestinationPath GameTheoryUtility.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameTheoryUtility
          path: GameTheoryUtility.zip
