name: Build, Publish, and Zip

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild GameTheoryUtility/GameTheoryUtility.csproj /t:Restore

      - name: Publish with MSBuild
        run: msbuild GameTheoryUtility/GameTheoryUtility.csproj /t:Publish /p:Configuration=Release /p:Platform="Any CPU"

      - name: Zip Publish Output
        run: |
          $publishDir = Get-ChildItem -Directory -Recurse -Filter publish | Select-Object -First 1
          Compress-Archive -Path "$($publishDir.FullName)\*" -DestinationPath GameTheoryUtility.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Game Theory Utility'
          path: GameTheoryUtility.zip
